# Generated by Django 5.2.10 on 2026-01-22 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_projectactivity_projectcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifiant')),
                ('subject', models.CharField(max_length=200, verbose_name="Objet de l'email")),
                ('html_template', models.TextField(help_text='Template HTML avec variables Django ({{ variable }})', verbose_name='Template HTML')),
                ('text_content', models.TextField(blank=True, help_text='Version texte brut (optionnel)', verbose_name='Contenu texte')),
                ('category', models.CharField(choices=[('prospection', 'Prospection'), ('follow_up', 'Relance'), ('proposal', 'Proposition'), ('meeting', 'Invitation RDV'), ('thank_you', 'Remerciement'), ('other', 'Autre')], default='prospection', max_length=50, verbose_name='Catégorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template email',
                'verbose_name_plural': 'Templates email',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifiée'), ('sending', "En cours d'envoi"), ('sent', 'Envoyée'), ('paused', 'En pause')], default='draft', max_length=20, verbose_name='Statut')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi planifiée")),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name="Début de l'envoi")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name="Fin de l'envoi")),
                ('total_sent', models.PositiveIntegerField(default=0, verbose_name='Total envoyés')),
                ('total_opened', models.PositiveIntegerField(default=0, verbose_name='Total ouverts')),
                ('total_clicked', models.PositiveIntegerField(default=0, verbose_name='Total cliqués')),
                ('total_replied', models.PositiveIntegerField(default=0, verbose_name='Total réponses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='messaging.emailtemplate', verbose_name='Template utilisé')),
            ],
            options={
                'verbose_name': 'Campagne email',
                'verbose_name_plural': 'Campagnes email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('bounced', 'Bounce')], default='pending', max_length=20, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Ouvert le')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Cliqué le')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
                ('message_id', models.CharField(blank=True, max_length=255, verbose_name='ID du message')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='messaging.emailcampaign')),
            ],
            options={
                'verbose_name': 'Destinataire de campagne',
                'verbose_name_plural': 'Destinataires de campagne',
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise")),
                ('contact_name', models.CharField(max_length=100, verbose_name='Nom du contact')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, max_length=500, verbose_name='Site web')),
                ('sector', models.CharField(blank=True, choices=[('btp', 'BTP / Construction'), ('commerce', 'Commerce'), ('services', 'Services'), ('restauration', 'Restauration'), ('sante', 'Santé'), ('transport', 'Transport / Logistique'), ('artisanat', 'Artisanat'), ('agriculture', 'Agriculture'), ('tourisme', 'Tourisme'), ('immobilier', 'Immobilier'), ('education', 'Éducation / Formation'), ('other', 'Autre')], max_length=20, verbose_name="Secteur d'activité")),
                ('activity_description', models.TextField(blank=True, verbose_name="Description de l'activité")),
                ('pain_points', models.TextField(blank=True, verbose_name='Points de douleur identifiés')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('interested', 'Intéressé'), ('meeting', 'RDV planifié'), ('proposal', 'Proposition envoyée'), ('negotiation', 'En négociation'), ('converted', 'Converti (Client)'), ('lost', 'Perdu'), ('not_interested', 'Pas intéressé')], default='new', max_length=20, verbose_name='Statut')),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('website', 'Site web'), ('referral', 'Recommandation'), ('cold_email', 'Email à froid'), ('event', 'Événement'), ('social', 'Réseaux sociaux'), ('other', 'Autre')], default='cold_email', max_length=20, verbose_name='Source')),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='1 = Très haute, 5 = Très basse', verbose_name='Priorité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('tags', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=500, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier contact')),
                ('next_follow_up', models.DateTimeField(blank=True, null=True, verbose_name='Prochain suivi')),
                ('converted_to_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_prospect', to='clients.clientprofile', verbose_name='Converti en client')),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='prospects',
            field=models.ManyToManyField(related_name='campaigns', through='messaging.CampaignRecipient', to='messaging.prospect', verbose_name='Prospects ciblés'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to='messaging.prospect'),
        ),
        migrations.CreateModel(
            name='ProspectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('email_sent', 'Email envoyé'), ('email_opened', 'Email ouvert'), ('email_clicked', 'Lien cliqué'), ('email_replied', 'Réponse reçue'), ('call', 'Appel téléphonique'), ('meeting', 'Rendez-vous'), ('note', 'Note ajoutée'), ('status_change', 'Changement de statut'), ('created', 'Prospect créé')], max_length=30, verbose_name="Type d'activité")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_activities', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='messaging.prospect', verbose_name='Prospect')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Envoyé'), ('inbound', 'Reçu')], default='outbound', max_length=10, verbose_name='Direction')),
                ('subject', models.CharField(max_length=300, verbose_name='Objet')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('html_content', models.TextField(blank=True, verbose_name='Contenu HTML')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Délivré'), ('opened', 'Ouvert'), ('clicked', 'Cliqué'), ('replied', 'Répondu'), ('failed', 'Échec'), ('received', 'Reçu')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Ouvert le')),
                ('message_id', models.CharField(blank=True, max_length=255, verbose_name='ID Brevo')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.emailcampaign', verbose_name='Campagne liée')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.prospect', verbose_name='Prospect')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_prospect_messages', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.emailtemplate', verbose_name='Template utilisé')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'prospect')},
        ),
    ]
