# Generated by Django 5.2.10 on 2026-01-22 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignrecipient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emailcampaign',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prospect',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prospectactivity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prospectmessage',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='prospects',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='prospectactivity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='prospectactivity',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='prospectmessage',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='prospectmessage',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='prospectmessage',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='prospectmessage',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='prospectmessage',
            name='template',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.prospect'),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.emailtemplate'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='total_clicked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='total_opened',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='total_replied',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='total_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_template',
            field=models.TextField(help_text='HTML content'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='text_content',
            field=models.TextField(blank=True, help_text='Plain text version'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='activity_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='converted_to_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='next_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='pain_points',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='source',
            field=models.CharField(default='cold_email', max_length=50),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('responded', 'A répondu'), ('converted', 'Converti'), ('archived', 'Archivé')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=255),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='prospectactivity',
            name='activity_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prospectactivity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prospectactivity',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='messaging.prospect'),
        ),
        migrations.AlterField(
            model_name='prospectmessage',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prospectmessage',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Reçu'), ('outbound', 'Envoyé')], default='outbound', max_length=10),
        ),
        migrations.AlterField(
            model_name='prospectmessage',
            name='message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prospectmessage',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospectmessage',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.prospect'),
        ),
        migrations.AlterField(
            model_name='prospectmessage',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('delivered', 'Reçu'), ('opened', 'Ouvert'), ('clicked', 'Cliqué'), ('failed', 'Échoué')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospectmessage',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='message_id',
        ),
    ]
