# Generated by Django 6.0.2 on 2026-02-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignrecipient',
            options={'verbose_name': 'Destinataire de campagne', 'verbose_name_plural': 'Destinataires de campagne'},
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'prospect')},
        ),
    ]
