"""Tests for the simulator report endpoint (email capture + PDF)."""
from __future__ import annotations

import json
from unittest.mock import patch

import pytest
from django.test import Client
from django.urls import reverse

from apps.simulateur.models import SimulatorReport


@pytest.mark.django_db
class TestSimulatorReportEndpoint:
    endpoint = '/simulateur/report/'

    def _payload(self, **overrides):
        base = {
            'email': 'dirigeant@acme.fr',
            'name': 'Jean Dupont',
            'company': 'Acme PME',
            'tool_slug': 'acse',
            'tool_name': 'Flux A.C.S.E',
            'snapshot': {
                'verdict': 'Flux fragile',
                'score': '5.2 / 10',
                'sections': [],
                'recommendations': ['Cartographier le tunnel commercial.'],
            },
            'consent': True,
            'website': '',
        }
        base.update(overrides)
        return base

    def test_happy_path_sends_email_and_persists(self):
        client = Client()
        with patch('apps.simulateur.services.SimulatorReportService.send') as mock_send:
            mock_send.return_value = None
            res = client.post(
                self.endpoint,
                data=json.dumps(self._payload()),
                content_type='application/json',
            )
        assert res.status_code == 200, res.content
        body = res.json()
        assert body['ok'] is True
        assert SimulatorReport.objects.filter(email='dirigeant@acme.fr').exists()
        mock_send.assert_called_once()

    def test_missing_consent_is_rejected(self):
        client = Client()
        res = client.post(
            self.endpoint,
            data=json.dumps(self._payload(consent=False)),
            content_type='application/json',
        )
        assert res.status_code == 400
        body = res.json()
        assert body['ok'] is False
        assert 'consent' in body.get('errors', {})

    def test_invalid_email_is_rejected(self):
        client = Client()
        res = client.post(
            self.endpoint,
            data=json.dumps(self._payload(email='not-an-email')),
            content_type='application/json',
        )
        assert res.status_code == 400

    def test_disposable_email_is_rejected(self):
        client = Client()
        res = client.post(
            self.endpoint,
            data=json.dumps(self._payload(email='x@mailinator.com')),
            content_type='application/json',
        )
        assert res.status_code == 400

    def test_honeypot_returns_fake_success_without_persisting(self):
        client = Client()
        res = client.post(
            self.endpoint,
            data=json.dumps(self._payload(website='http://spam.example')),
            content_type='application/json',
        )
        assert res.status_code == 200
        assert res.json()['ok'] is True
        assert not SimulatorReport.objects.exists()

    def test_get_is_not_allowed(self):
        client = Client()
        res = client.get(self.endpoint)
        assert res.status_code == 405

    def test_download_mode_returns_pdf_base64(self):
        """delivery=download must return PDF bytes in base64 for client-side download."""
        import base64
        client = Client()
        with patch('apps.simulateur.services.SimulatorReportService.send') as mock_send:
            mock_send.return_value = None
            res = client.post(
                self.endpoint,
                data=json.dumps(self._payload(delivery='download')),
                content_type='application/json',
            )
        assert res.status_code == 200, res.content
        body = res.json()
        assert body['ok'] is True
        assert body.get('delivery') == 'download'
        assert body.get('filename', '').endswith('.pdf')
        pdf_b64 = body.get('pdf_base64')
        assert pdf_b64, 'pdf_base64 missing'
        pdf_bytes = base64.b64decode(pdf_b64)
        assert pdf_bytes[:5] == b'%PDF-'
        # send() must still be called (email copy) with pre-generated bytes
        mock_send.assert_called_once()
        _, kwargs = mock_send.call_args
        assert 'pdf_bytes' in kwargs and kwargs['pdf_bytes'] == pdf_bytes

    def test_chart_payload_is_forwarded_without_persisting_base64(self):
        client = Client()
        chart_payload = [
            {
                'title': 'Coûts vs chiffre d\'affaires',
                'x_label': 'Nombre de ventes',
                'y_label': 'Euros (€)',
                'series': ['Coûts totaux', 'Chiffre d\'affaires'],
                'data_url': 'data:image/png;base64,AAA',
            }
        ]

        with patch('apps.simulateur.services.SimulatorReportService.send') as mock_send:
            mock_send.return_value = None
            res = client.post(
                self.endpoint,
                data=json.dumps(self._payload(snapshot={
                    'verdict': 'Flux fragile',
                    'score': '5.2 / 10',
                    'sections': [],
                    'recommendations': ['Cartographier le tunnel commercial.'],
                    'charts': chart_payload,
                })),
                content_type='application/json',
            )

        assert res.status_code == 200, res.content
        report = SimulatorReport.objects.get(email='dirigeant@acme.fr')
        assert 'charts' not in report.snapshot
        assert '_charts' not in report.snapshot

        mock_send.assert_called_once()
        _, kwargs = mock_send.call_args
        assert kwargs['charts'] == chart_payload


@pytest.mark.django_db
class TestSimulatorReportRobustness:
    """Garde-fous du téléchargement PDF (régression : erreur générique).

    Des graphiques haute résolution suffisaient à faire dépasser le cap de
    taille du snapshot : la requête était rejetée en 400 sans `message`, et
    l'utilisateur ne voyait qu'un « Une erreur est survenue » opaque.
    """

    endpoint = '/simulateur/report/'

    @staticmethod
    def _chart(size_bytes: int, title: str = 'Graphique'):
        return {
            'title': title,
            'x_label': 'Ventes',
            'y_label': 'Euros (€)',
            'series': ['Coûts'],
            'data_url': 'data:image/png;base64,' + ('A' * size_bytes),
        }

    def _payload(self, charts, **overrides):
        base = {
            'email': 'dirigeant@acme.fr',
            'name': 'Jean Dupont',
            'company': 'Acme PME',
            'tool_slug': 'point-mort',
            'tool_name': 'Seuil de Rentabilité',
            'delivery': 'download',
            'consent': True,
            'website': '',
            'snapshot': {
                'user_inputs': [{'label': 'Charges fixes', 'value': '4200'}],
                'results': [{'label': 'Point mort', 'value': '18 400 €'}],
                'charts': charts,
            },
        }
        base.update(overrides)
        return base

    def _post(self, payload):
        client = Client()
        with patch('apps.simulateur.services.SimulatorReportService.send'):
            return client.post(
                self.endpoint,
                data=json.dumps(payload),
                content_type='application/json',
            )

    def test_heavy_charts_still_return_a_pdf(self):
        """4 graphiques haute résolution (~2,4 Mo) : téléchargement OK."""
        import base64

        charts = [self._chart(600_000, f'Graphique {i}') for i in range(4)]
        res = self._post(self._payload(charts))

        assert res.status_code == 200, res.content
        body = res.json()
        assert body['ok'] is True
        assert base64.b64decode(body['pdf_base64'])[:5] == b'%PDF-'

    def test_charts_over_budget_are_trimmed_not_rejected(self):
        """Au-delà du budget, les graphiques sont écartés — pas la demande."""
        from apps.simulateur.forms import SimulatorReportForm

        oversized = SimulatorReportForm.MAX_CHARTS_BYTES // 2 + 1
        charts = [self._chart(oversized, f'Graphique {i}') for i in range(4)]

        with patch(
            'apps.simulateur.services.SimulatorReportService.generate_pdf',
            return_value=b'%PDF-stub',
        ) as mock_pdf, patch(
            'apps.simulateur.services.SimulatorReportService.send'
        ):
            client = Client()
            res = client.post(
                self.endpoint,
                data=json.dumps(self._payload(charts)),
                content_type='application/json',
            )

        assert res.status_code == 200, res.content
        forwarded = mock_pdf.call_args.kwargs['charts']
        assert len(forwarded) == 1, 'budget must cap the forwarded charts'
        assert forwarded[0]['title'] == 'Graphique 0'

    def test_validation_error_carries_a_readable_message(self):
        """Le front affiche `message` : il doit toujours être renseigné."""
        payload = self._payload([], consent=False)
        res = self._post(payload)

        assert res.status_code == 400
        body = res.json()
        assert body['ok'] is False
        message = body.get('message')
        assert message, 'message is required by the front-end'
        assert message != 'Une erreur est survenue. Réessayez.'
        assert 'errors' in body

    def test_pdf_render_falls_back_to_no_charts(self):
        """Si le rendu échoue avec les graphiques, on retente sans eux."""
        import base64

        calls = []

        def _generate(report, *, charts=None):
            calls.append(charts)
            if charts:
                raise RuntimeError('WeasyPrint: image décodée invalide')
            return b'%PDF-fallback'

        with patch(
            'apps.simulateur.services.SimulatorReportService.generate_pdf',
            side_effect=_generate,
        ), patch('apps.simulateur.services.SimulatorReportService.send'):
            client = Client()
            res = client.post(
                self.endpoint,
                data=json.dumps(self._payload([self._chart(1000)])),
                content_type='application/json',
            )

        assert res.status_code == 200, res.content
        assert base64.b64decode(res.json()['pdf_base64']) == b'%PDF-fallback'
        assert len(calls) == 2 and calls[1] is None

    def test_pdf_failure_without_charts_reports_a_message(self):
        """Échec irrécupérable : message explicite, pas de fallback opaque."""
        with patch(
            'apps.simulateur.services.SimulatorReportService.generate_pdf',
            side_effect=RuntimeError('boom'),
        ), patch('apps.simulateur.services.SimulatorReportService.send'):
            client = Client()
            res = client.post(
                self.endpoint,
                data=json.dumps(self._payload([])),
                content_type='application/json',
            )

        assert res.status_code == 500
        body = res.json()
        assert body['ok'] is False
        assert 'PDF' in body['message']


@pytest.mark.django_db
class TestSimulatorReportModalMarkup:
    """Le modal doit exposer un `tool_slug` que le serveur accepte.

    Régression : les attributs `data-tool-*` passaient par `escapejs`, filtre
    destiné aux littéraux JavaScript, qui échappe le tiret (`-` → `\\u002D`).
    Dans un attribut HTML, `dataset.toolSlug` relisait « point\\u002Dmort » :
    le SlugField rejetait la valeur et aucun rapport n'était généré pour les
    22 outils (sur 30) dont le slug contient un tiret.
    """

    @staticmethod
    def _tool_url_names():
        from apps.simulateur import urls as simulateur_urls

        skipped = {'hub', 'report_submit', 'conformite-facture-check'}
        return [
            pattern.name
            for pattern in simulateur_urls.urlpatterns
            if pattern.name and pattern.name not in skipped
        ]

    @staticmethod
    def _data_attr(html: str, attr: str) -> str:
        import re

        match = re.search(rf'{attr}="([^"]*)"', html)
        assert match, f'{attr} absent du modal'
        return match.group(1)

    def test_every_tool_page_exposes_a_valid_slug(self):
        import html as html_lib

        from apps.simulateur.forms import SimulatorReportForm

        client = Client()
        checked = 0
        for url_name in self._tool_url_names():
            url = reverse(f'simulateur:{url_name}')
            res = client.get(url)
            if res.status_code != 200:
                continue
            body = res.content.decode()
            if 'data-tool-slug' not in body:
                continue
            checked += 1

            slug = html_lib.unescape(self._data_attr(body, 'data-tool-slug'))
            assert '\\u' not in slug, f'{url_name}: slug échappé « {slug} »'

            # Le slug rendu doit passer la validation serveur telle quelle.
            form = SimulatorReportForm({
                'email': 'dirigeant@acme.fr',
                'tool_slug': slug,
                'tool_name': 'Outil',
                'snapshot': {},
                'consent': True,
                'website': '',
            })
            assert form.is_valid(), f'{url_name}: {form.errors.as_json()}'

        assert checked >= 20, f'seulement {checked} pages outils vérifiées'

    def test_tool_name_is_not_js_escaped(self):
        """Les apostrophes ne doivent pas fuir en « \\u0027 » dans le PDF."""
        import html as html_lib

        client = Client()
        res = client.get(reverse('simulateur:cac'))
        assert res.status_code == 200

        name = html_lib.unescape(
            self._data_attr(res.content.decode(), 'data-tool-name')
        )
        assert name == "Coût d'Acquisition", name
