# Generated by Django 6.0.2 on 2026-03-02 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0011_populate_from_devis_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='📚', help_text='Emoji pour la catégorie', max_length=10, verbose_name='Icône emoji')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AcademyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('seo', '🔍 SEO'), ('content', '📝 Content Marketing'), ('email', '📧 Email Marketing'), ('social', '📱 Social Media'), ('analytics', '📊 Analytics'), ('design', '🎨 Design Web'), ('conversion', '🎯 Conversion Optimization'), ('growth', '📈 Growth Hacking')], max_length=50, verbose_name='Catégorie')),
                ('level', models.CharField(choices=[('beginner', '🟢 Débutant'), ('intermediate', '🟡 Intermédiaire'), ('advanced', '🔴 Avancé')], max_length=20, verbose_name='Niveau')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('learning_objectives', models.JSONField(default=list, help_text='["Comprendre les principes SEO", "Optimiser Meta", ...]', verbose_name="Objectifs d'apprentissage")),
                ('estimated_duration_hours', models.PositiveIntegerField(default=2, verbose_name='Durée estimée (h)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'élèves")),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Note moyenne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo', verbose_name='Lien vidéo')),
                ('video_duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Durée vidéo (min)')),
                ('content', models.TextField(verbose_name='Contenu (Markdown)')),
                ('resources', models.JSONField(default=list, help_text='[{"title": "PDF", "url": "..."}, ...]', verbose_name='Ressources')),
                ('quiz_content', models.JSONField(blank=True, default=dict, help_text='{"questions": [{"question": "...", "answers": [...], "correct": 0}]}', verbose_name='Quiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='resources.academycourse')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ClientCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Inscrit'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('abandoned', 'Abandonné')], default='enrolled', max_length=20, verbose_name='Statut')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='Progression (%)')),
                ('certificate_earned', models.BooleanField(default=False, verbose_name='Certificat obtenu')),
                ('certificate_url', models.URLField(blank=True, verbose_name='URL certificat')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Débuté le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='clients.clientprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.academycourse')),
            ],
            options={
                'verbose_name': 'Inscription cours',
                'verbose_name_plural': 'Inscriptions cours',
                'ordering': ['-enrolled_at'],
                'unique_together': {('client', 'course')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(help_text='Description courte pour les listes', max_length=255, verbose_name='Résumé')),
                ('content', models.TextField(help_text='Markdown supporté', verbose_name='Contenu')),
                ('difficulty', models.CharField(choices=[('beginner', '🟢 Débutant'), ('intermediate', '🟡 Intermédiaire'), ('advanced', '🔴 Avancé')], default='beginner', max_length=20, verbose_name='Difficulté')),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='Temps de lecture (min)')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, Loom...', verbose_name='URL vidéo tutoriel')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Votes utiles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='resources.knowledgecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('articles', models.ManyToManyField(blank=True, related_name='tags', to='resources.knowledgearticle')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(help_text='Markdown supporté', verbose_name='Réponse')),
                ('audience', models.CharField(choices=[('all', 'Tous'), ('prospect', 'Prospects'), ('client', 'Clients')], default='all', max_length=20, verbose_name='Audience')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='resources.knowledgecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.PositiveIntegerField(verbose_name='Score (%)')),
                ('answers', models.JSONField(verbose_name='Réponses')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.clientcourseenrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.academylesson')),
            ],
            options={
                'verbose_name': 'Résultat quiz',
                'verbose_name_plural': 'Résultats quiz',
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
