# Generated by Django 5.2.10 on 2026-05-29 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factures', '0022_einvoicing_phase1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('DRAFT', 'Brouillon (non soumise)'), ('SUBMITTED', 'Soumise à la PDP'), ('QUEUED', "En file d'attente PDP"), ('SENT', 'Transmise au destinataire'), ('DELIVERED', 'Réceptionnée par destinataire'), ('APPROVED', 'Approuvée par destinataire'), ('REJECTED', 'Refusée par destinataire'), ('DISPUTED', 'Litige'), ('PAID', 'Encaissée (déclaration paiement)'), ('CANCELLED', 'Annulée (avant transmission)'), ('ARCHIVED', 'Archivée')], max_length=20, verbose_name='État')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Survenu le')),
                ('source', models.CharField(default='system', help_text="Origine de l'événement (admin, api, webhook, system, dunning, etc.)", max_length=40, verbose_name='Source')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Métadonnées libres (ID PDP externe, motif rejet, etc.) — pas de PII inutile.', verbose_name='Données')),
                ('previous_hash', models.CharField(editable=False, help_text="Hash de l'événement précédent de la même facture (ou genesis).", max_length=64, verbose_name='Hash précédent')),
                ('event_hash', models.CharField(editable=False, help_text="SHA-256 chaîné garantissant l'intégrité de l'historique.", max_length=64, unique=True, verbose_name="Hash de l'événement")),
                ('actor', models.ForeignKey(blank=True, help_text="Utilisateur Django à l'origine de l'événement, si applicable.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='factures.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Événement cycle de vie facture',
                'verbose_name_plural': 'Événements cycle de vie factures',
                'ordering': ('invoice_id', 'occurred_at', 'id'),
                'indexes': [models.Index(fields=['invoice', 'state'], name='idx_lc_invoice_state'), models.Index(fields=['state', 'occurred_at'], name='idx_lc_state_time')],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'previous_hash'), name='uniq_lifecycle_invoice_prev_hash')],
            },
        ),
    ]
