# Generated by Django 5.2.12 on 2026-04-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0010_alter_lead_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Nom')),
                ('company', models.CharField(blank=True, max_length=180, verbose_name='Entreprise')),
                ('tool_slug', models.SlugField(max_length=64, verbose_name='Outil (slug)')),
                ('tool_name', models.CharField(max_length=120, verbose_name='Outil (nom)')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Données snapshot')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('pdf_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('send_error', models.TextField(blank=True, verbose_name="Erreur d'envoi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('converted_to_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulator_reports', to='leads.lead', verbose_name='Lead converti')),
            ],
            options={
                'verbose_name': 'Rapport simulateur',
                'verbose_name_plural': 'Rapports simulateur',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='idx_simreport_email'), models.Index(fields=['tool_slug'], name='idx_simreport_tool'), models.Index(fields=['created_at'], name='idx_simreport_created')],
            },
        ),
    ]
