# Generated by Django 5.2.15 on 2026-06-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulateur", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulatorreport",
            name="send_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Incrémenté à chaque tentative ; plafonne les renvois du cron.",
                verbose_name="Tentatives d'envoi",
            ),
        ),
    ]
