# Generated by Django 5.2.5 on 2025-10-30 01:24

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Numéro de devis format NE-AAAA-####, généré automatiquement.', max_length=20, unique=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Rejeté')], default='draft', max_length=20)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='devis.client')),
                ('service', models.ForeignKey(blank=True, help_text='Service principal demandé (optionnel si plusieurs items).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text="Libellé si aucun service n'est associé.", max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Taux de TVA en pourcentage (ex. 20.00 pour 20\xa0%).', max_digits=4)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_items', to='devis.quote')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='services.service')),
            ],
            options={
                'verbose_name': 'ligne de devis',
                'verbose_name_plural': 'lignes de devis',
            },
        ),
    ]
