# Generated by Django 5.2.5 on 2025-10-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='number',
            field=models.CharField(blank=True, help_text='Numéro de devis format DEV-AAAA-XXX, généré automatiquement.', max_length=20, unique=True),
        ),
    ]
