# Generated by Django 5.2.6 on 2025-11-08 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_alter_quote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='devis'),
        ),
        migrations.CreateModel(
            name='QuotePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='devis/photos')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='devis.quote')),
            ],
            options={
                'verbose_name': 'photo du devis',
                'verbose_name_plural': 'photos du devis',
            },
        ),
    ]
