# Generated by Django 5.2.8 on 2025-12-10 01:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_quote_pdf_quotephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('processed', 'Traité'), ('rejected', 'Rejeté')], default='new', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'demande de devis',
                'verbose_name_plural': 'demandes de devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='devis/requests/photos', verbose_name='Fichier')),
            ],
            options={
                'verbose_name': 'photo de demande de devis',
                'verbose_name_plural': 'photos de demandes de devis',
            },
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('invoiced', 'Facturé')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='description',
            field=models.CharField(help_text='Libellé de la ligne (prérempli si un service est sélectionné).', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Taux de TVA en pourcentage (ex. 20.00 pour 20\xa0%).', max_digits=4, verbose_name='Taux de TVA'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix unitaire HT'),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_request',
            field=models.ForeignKey(blank=True, help_text="Demande d'origine (facultative).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='devis.quoterequest'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='quote_requests', to='devis.quoterequestphoto', verbose_name='Photos'),
        ),
    ]
