# Generated by Django 5.2.9 on 2026-01-03 17:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0006_quote_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taux de TVA en pourcentage (ex. 20.00 pour 20\xa0%).', max_digits=4, verbose_name='Taux de TVA'),
        ),
    ]
