# Generated by Django 5.2.10 on 2026-01-16 11:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0007_alter_quoteitem_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Montant de l'acompte encaissé", max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='deposit_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='signature_audit_trail',
            field=models.JSONField(blank=True, help_text="Informations d'audit de la signature", null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='signature_image',
            field=models.FileField(blank=True, help_text='Signature électronique du client', null=True, upload_to='devis/signatures'),
        ),
        migrations.AddField(
            model_name='quote',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, help_text="ID de session Stripe pour le paiement d'acompte", max_length=255),
        ),
    ]
