# Generated by Django 5.2.10 on 2026-02-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0008_quote_deposit_paid_quote_deposit_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='included_support_months',
            field=models.IntegerField(default=0, help_text='Nombre de mois de support inclus'),
        ),
        migrations.AddField(
            model_name='quote',
            name='installment_plan',
            field=models.CharField(blank=True, help_text="Plan d'échelonnement (ex: '3x', '12x')", max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='money_back_guarantee',
            field=models.BooleanField(default=False, help_text='Condition de remboursement'),
        ),
        migrations.AddField(
            model_name='quote',
            name='unlimited_revisions',
            field=models.BooleanField(default=False, help_text='Révisions illimitées incluses'),
        ),
    ]
