# Generated by Django 6.0.2 on 2026-02-24 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0009_quote_included_support_months_quote_installment_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de validation', null=True, verbose_name='Validé le'),
        ),
        migrations.AddField(
            model_name='quote',
            name='validated_audit_trail',
            field=models.JSONField(blank=True, default=dict, help_text='Métadonnées : {ip, user_agent, timestamp, comment, etc.}', verbose_name='Audit trail validation'),
        ),
        migrations.AddField(
            model_name='quote',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a validé le devis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('validated', 'Validé'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('invoiced', 'Facturé')], default='draft', max_length=20),
        ),
    ]
