# Generated by Django 5.2.10 on 2026-02-25 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0010_quote_validated_at_quote_validated_audit_trail_and_more'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': 'devis', 'verbose_name_plural': 'devis'},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='idx_devis_client_email'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='idx_quote_status'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['issue_date'], name='idx_quote_issue_date'),
        ),
    ]
