# Generated by Django 6.0.2 on 2026-02-26 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0014_remove_quote_legacy_option_fields'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quote',
            name='idx_quote_status',
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', '-created_at'], name='idx_quote_status_date'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['public_token'], name='idx_quote_token'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['client', 'status'], name='idx_quote_client_status'),
        ),
    ]
