# Generated by Django 6.0.2 on 2026-03-01 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0017_backfill_linked_profile'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='idx_client_linked_profile',
        ),
        migrations.RemoveIndex(
            model_name='quote',
            name='idx_quote_status_date',
        ),
        migrations.RemoveIndex(
            model_name='quote',
            name='idx_quote_token',
        ),
        migrations.RemoveIndex(
            model_name='quote',
            name='idx_quote_client_status',
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='idx_quote_status'),
        ),
    ]
