# Generated by Django 6.0.2 on 2026-03-04 21:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0019_merge_quote_client_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='line_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remise en pourcentage appliquée à cette ligne (ex. 10.00 pour 10 %).', max_digits=5, verbose_name='Remise ligne (%)'),
        ),
    ]
