# Generated by Django 5.2.10 on 2026-03-27 18:00

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0020_add_line_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=core.utils.raw_media_storage, upload_to='devis'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='signature_image',
            field=models.FileField(blank=True, help_text='Signature électronique du client', null=True, storage=core.utils.raw_media_storage, upload_to='devis/signatures'),
        ),
    ]
