# Generated by Django 5.2.10 on 2026-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('project_type', models.CharField(choices=[('vitrine', 'Site Vitrine'), ('ecommerce', 'E‑commerce'), ('plateforme', 'Plateforme / Mini‑ERP')], max_length=20)),
                ('message', models.TextField()),
                ('budget', models.CharField(blank=True, choices=[('small', '< 3\xa0000 €'), ('medium', '3\xa0000 € – 8\xa0000 €'), ('large', '8\xa0000 € – 15\xa0000 €'), ('enterprise', '> 15\xa0000 €'), ('discuss', 'À discuter')], max_length=20)),
                ('existing_url', models.URLField(blank=True, max_length=500)),
                ('attachment', models.FileField(blank=True, upload_to='leads/attachments/')),
                ('honeypot', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
