# Generated by Django 5.2.10 on 2026-01-22 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('category', models.CharField(choices=[('prospection', 'Prospection'), ('remerciement', 'Remerciement'), ('relance', 'Relance'), ('proposition', 'Proposition commerciale'), ('confirmation', 'Confirmation de rendez-vous'), ('suivi', 'Suivi de projet')], max_length=20, verbose_name='Catégorie')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('body_html', models.TextField(verbose_name='Corps HTML')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Template d'email",
                'verbose_name_plural': "Templates d'email",
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='attachment',
            field=models.FileField(blank=True, upload_to='leads/attachments/', verbose_name='Pièce jointe'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.CharField(blank=True, choices=[('small', '< 3\xa0000 €'), ('medium', '3\xa0000 € – 8\xa0000 €'), ('large', '8\xa0000 € – 15\xa0000 €'), ('enterprise', '> 15\xa0000 €'), ('discuss', 'À discuter')], max_length=20, verbose_name='Budget estimé'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='existing_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Site existant'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='project_type',
            field=models.CharField(choices=[('vitrine', 'Site Vitrine'), ('ecommerce', 'E‑commerce'), ('plateforme', 'Plateforme / Mini‑ERP')], max_length=20, verbose_name='Type de projet'),
        ),
        migrations.CreateModel(
            name='EmailComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_emails', models.TextField(help_text='Séparés par des virgules', verbose_name='Destinataires (To)')),
                ('cc_emails', models.TextField(blank=True, help_text='Séparés par des virgules', verbose_name='CC')),
                ('bcc_emails', models.TextField(blank=True, help_text='Séparés par des virgules', verbose_name='BCC')),
                ('subject', models.CharField(max_length=500, verbose_name='Sujet')),
                ('body_html', models.TextField(verbose_name='Corps HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Brouillon')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.emailtemplate', verbose_name='Template utilisé')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
