# Generated by Django 5.2.10 on 2026-01-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='attachment',
            field=models.FileField(blank=True, upload_to='leads/attachments/', verbose_name='Pièce jointe'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.CharField(blank=True, choices=[('small', '< 3\xa0000 €'), ('medium', '3\xa0000 € – 8\xa0000 €'), ('large', '8\xa0000 € – 15\xa0000 €'), ('enterprise', '> 15\xa0000 €'), ('discuss', 'À discuter')], max_length=20, verbose_name='Budget estimé'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='existing_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Site existant'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='project_type',
            field=models.CharField(choices=[('vitrine', 'Site Vitrine'), ('ecommerce', 'E‑commerce'), ('plateforme', 'Plateforme / Mini‑ERP')], max_length=20, verbose_name='Type de projet'),
        ),
    ]
