# Generated by Django 5.2.10 on 2026-01-22 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_attachment_alter_lead_budget_and_more'),
        ('leads', '0002_emailtemplate_alter_lead_attachment_and_more'),
    ]

    operations = [
    ]
