# Generated by Django 5.2.10 on 2026-01-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_merge_20260122_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(choices=[('prospection', '🎯 Prospection'), ('relance', '🔄 Relance'), ('devis', '💼 Devis'), ('remerciement', '🙏 Remerciement'), ('bons_plans', '🎁 Bons plans'), ('confirmation', '✅ Confirmation'), ('suivi', '📊 Suivi de projet'), ('bienvenue', '👋 Bienvenue'), ('anniversaire', '🎂 Anniversaire'), ('newsletter', '📰 Newsletter'), ('satisfaction', '⭐ Satisfaction'), ('parrainage', '🤝 Parrainage')], max_length=20, verbose_name='Catégorie'),
        ),
    ]
