# Generated by Django 6.0.2 on 2026-02-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_add_email_template_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='project_type',
            field=models.CharField(choices=[('site', 'Site'), ('commerce', 'Commerce'), ('outils_metier', 'Outils métier'), ('other', 'Autre')], max_length=20, verbose_name='Type de projet'),
        ),
    ]
