# Generated by Django 6.0.2 on 2026-02-25 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_must_change_password_and_doc_types'),
        ('leads', '0005_alter_lead_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de conversion'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_to_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='clients.clientprofile', verbose_name='Client converti'),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', '🆕 Nouveau'), ('contacted', '📧 Contacté'), ('qualified', '✅ Qualifié'), ('converted', '🎉 Converti'), ('lost', '❌ Perdu')], default='new', max_length=20, verbose_name='Statut'),
        ),
    ]
