# Generated by Django 5.2.10 on 2026-02-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientnotification_idx_notif_client_read_and_more'),
        ('leads', '0006_alter_lead_options_lead_converted_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='idx_lead_status'),
        ),
    ]
