# Generated by Django 6.0.2 on 2026-03-01 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_idx_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='attachment',
            field=models.FileField(blank=True, upload_to='leads/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'webp', 'zip'])], verbose_name='Pièce jointe'),
        ),
    ]
