# Generated by Django 5.2.10 on 2026-03-27 15:19

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_lead_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Téléphone'),
        ),
    ]
