# Generated by Django 5.2.10 on 2026-03-27 18:00

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='attachment',
            field=models.FileField(blank=True, storage=core.utils.raw_media_storage, upload_to='leads/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'webp', 'zip'])], verbose_name='Pièce jointe'),
        ),
    ]
