# Generated by Django 5.2.12 on 2026-04-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_lead_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('source', models.CharField(choices=[('footer', 'Footer'), ('article', "Fin d'article"), ('simulateur', 'Simulateur'), ('popup', 'Popup')], default='footer', max_length=20, verbose_name='Source')),
                ('source_detail', models.CharField(blank=True, help_text='Slug article, nom simulateur, etc.', max_length=200, verbose_name='Détail source')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='idx_subscriber_active')],
            },
        ),
    ]
