# Generated by Django 5.2.12 on 2026-04-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_add_email_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Score automatique 0-100 basé sur budget, type de projet et complétude.', verbose_name='Score'),
        ),
    ]
