# Generated by Django 5.2.12 on 2026-04-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_add_lead_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('body_html', models.TextField(help_text='Contenu de la newsletter. Sera injecté dans le template premium TUS.', verbose_name='Contenu HTML')),
                ('status', models.CharField(choices=[('draft', '📝 Brouillon'), ('sending', "📤 En cours d'envoi"), ('sent', '✅ Envoyée'), ('failed', '❌ Échouée')], default='draft', max_length=20, verbose_name='Statut')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Destinataires')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Envoyés')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Échecs')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyée le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campagne newsletter',
                'verbose_name_plural': 'Campagnes newsletter',
                'ordering': ['-created_at'],
            },
        ),
    ]
