# Generated by Django 5.2.10 on 2026-01-24 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Résumé')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='chroniques/covers/', verbose_name='Image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-publish_date'],
            },
        ),
    ]
