# Generated by Django 6.0.2 on 2026-03-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniques', '0003_alter_article_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description pour Google (160 chars max). Si vide, utilise le résumé.', max_length=160, verbose_name='Meta description'),
        ),
    ]
