# Generated by Django 5.2.10 on 2026-04-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniques', '0005_add_category_and_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='credits_image',
            field=models.CharField(blank=True, help_text="Crédits pour l'image de couverture", max_length=255, verbose_name='Crédits image'),
        ),
    ]
