# Generated by Django 5.2.10 on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniques', '0006_article_credits_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
    ]