# Generated by Django 5.2.5 on 2025-10-30 19:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, help_text='Numéro NE-AAAA-####, généré automatiquement si vide.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
    ]
