# Generated by Django 5.2.5 on 2025-10-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_invoice_notes_invoice_payment_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Devis'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('partial', 'Partiellement payée'), ('overdue', 'En retard')], default='draft', max_length=20),
        ),
    ]
