# Generated by Django 3.2.25 on 2025-11-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_alter_invoice_number_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('refacturation', 'Refacturation'), ('avoir', 'Avoir'), ('demo', 'Devis'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('ok', ' '), ('partial', 'Partiellement payée'), ('overdue', 'En retard')], default='draft', max_length=20),
        ),
    ]
