# Generated by Django 5.2.8 on 2025-12-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('refacturation', 'Refacturation'), ('avoir', 'Avoir'), ('demo', 'Devis'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('partial', 'Partiellement payée'), ('overdue', 'En retard')], default='draft', max_length=20),
        ),
    ]
