# Generated by Django 5.2.8 on 2025-12-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0006_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='command_ref',
            field=models.CharField(blank=True, help_text='Référence bon de commande client.', max_length=100),
        ),
    ]
