# Generated by Django 5.2.10 on 2026-01-16 11:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0007_invoice_command_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant total encaissé', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='public_token',
            field=models.CharField(blank=True, help_text='Jeton public pour accès client', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, help_text='ID de session Stripe pour le paiement', max_length=255),
        ),
    ]
