# Generated by Django 5.2.10 on 2026-01-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0008_invoice_amount_paid_invoice_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dunning_completed',
            field=models.BooleanField(default=False, help_text='Si True, plus de relances automatiques'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_date',
            field=models.DateTimeField(blank=True, help_text='Date de la dernière relance', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_level',
            field=models.PositiveSmallIntegerField(default=0, help_text='Niveau de la dernière relance envoyée (0 = aucune)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Nombre total de relances envoyées'),
        ),
    ]
