# Generated by Django 5.2.10 on 2026-01-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0009_invoice_dunning_completed_invoice_last_reminder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='dunning_completed',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='last_reminder_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='last_reminder_level',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='reminder_count',
        ),
    ]
