# Generated by Django 5.2.10 on 2026-01-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0010_remove_invoice_dunning_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dunning_completed',
            field=models.BooleanField(default=False, help_text='Processus de relance terminé (4 relances envoyées)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_date',
            field=models.DateField(blank=True, help_text='Date de la dernière relance envoyée', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_level',
            field=models.IntegerField(default=0, help_text='Niveau de relance (0=aucune, 1=soft, 2=firm, 3=urgent, 4=final)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_count',
            field=models.IntegerField(default=0, help_text='Nombre total de relances envoyées'),
        ),
    ]
