# Generated by Django 6.0.2 on 2026-02-24 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0011_invoice_dunning_completed_invoice_last_reminder_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a marqué la facture comme payée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_marked_paid', to=settings.AUTH_USER_MODEL, verbose_name='Marquée payée par'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_audit_trail',
            field=models.JSONField(blank=True, default=dict, help_text='Métadonnées : {ip, user_agent, timestamp, comment, etc.}', verbose_name='Audit trail paiement'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Document/reçu de paiement (virement, chèque, etc.)', null=True, upload_to='factures/proofs/', verbose_name='Preuve de paiement'),
        ),
    ]
