# Generated by Django 5.2.10 on 2026-02-25 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0011_alter_quote_options_client_idx_devis_client_email_and_more'),
        ('factures', '0012_invoice_paid_by_invoice_payment_audit_trail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='idx_invoice_status'),
        ),
    ]
