# Generated by Django 6.0.2 on 2026-02-25 20:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0013_invoice_idx_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('refacturation', 'Refacturation'), ('avoir', 'Avoir'), ('demo', 'Démonstration'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('partial', 'Partiellement payée'), ('overdue', 'En retard')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
    ]
