# Generated by Django 5.2.10 on 2026-02-25 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0014_remove_quote_legacy_option_fields'),
        ('factures', '0014_alter_invoice_status_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client facturé (rempli auto depuis le devis).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='devis.client', verbose_name='Client'),
        ),
    ]
