# Generated by Django 6.0.2 on 2026-02-27 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0015_add_performance_indexes'),
        ('factures', '0016_populate_invoice_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='idx_invoice_client_status'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['quote'], name='idx_invoice_quote'),
        ),
    ]
