# Generated by Django 6.0.2 on 2026-03-02 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_populate_from_devis_client'),
        ('factures', '0018_merge_invoice_client_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client facturé (rempli auto depuis le devis).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clients.clientprofile', verbose_name='Client'),
        ),
    ]
