# Generated by Django 6.0.2 on 2026-03-04 21:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0019_align_invoice_client_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='line_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remise en pourcentage appliquée à cette ligne.', max_digits=5, verbose_name='Remise ligne (%)'),
        ),
    ]
