# Generated by Django 5.2.10 on 2026-03-27 18:00

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0020_add_line_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Document/reçu de paiement (virement, chèque, etc.)', null=True, storage=core.utils.raw_media_storage, upload_to='factures/proofs/', verbose_name='Preuve de paiement'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=core.utils.raw_media_storage, upload_to='factures'),
        ),
    ]
