# Generated by Django 5.2.10 on 2026-05-29 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0021_alter_invoice_payment_proof_alter_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer_reference',
            field=models.CharField(blank=True, help_text="BT-10 EN 16931 — référence fournie par l'acheteur.", max_length=100, verbose_name='Référence acheteur'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence contrat'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='credit_note_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='factures.invoice', verbose_name='Avoir relatif à la facture'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency_code',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Devise (ISO 4217)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(blank=True, help_text="À renseigner si différente de la date d'émission.", null=True, verbose_name='Date de livraison / exécution'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fin période'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Début période'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type_code',
            field=models.CharField(choices=[('380', 'Commercial invoice (facture commerciale)'), ('381', 'Credit note (avoir)'), ('383', 'Debit note (note de débit)'), ('384', 'Corrected invoice (facture rectificative)'), ('389', 'Self-billed invoice (autofacturation)'), ('386', "Prepayment invoice (facture d'acompte)")], default='380', help_text='380 facture, 381 avoir, 386 acompte, 384 rectificative.', max_length=4, verbose_name='Code type de facture (UNTDID 1001)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_credit_note',
            field=models.BooleanField(default=False, help_text='Coché pour les avoirs (génère une numérotation AVO-AAAA-XXXXX).', verbose_name='Avoir'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lifecycle_state',
            field=models.CharField(choices=[('DRAFT', 'Brouillon (non soumise)'), ('SUBMITTED', 'Soumise à la PDP'), ('QUEUED', "En file d'attente PDP"), ('SENT', 'Transmise au destinataire'), ('DELIVERED', 'Réceptionnée par destinataire'), ('APPROVED', 'Approuvée par destinataire'), ('REJECTED', 'Refusée par destinataire'), ('DISPUTED', 'Litige'), ('PAID', 'Encaissée (déclaration paiement)'), ('CANCELLED', 'Annulée (avant transmission)'), ('ARCHIVED', 'Archivée')], db_index=True, default='DRAFT', help_text='État synchronisé avec la PDP — détaillé dans InvoiceLifecycleEvent.', max_length=20, verbose_name='État cycle de vie PDP'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order_ref',
            field=models.CharField(blank=True, help_text='Référence du BdC client (BT-13).', max_length=100, verbose_name='Référence bon de commande'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_type',
            field=models.CharField(choices=[('GOODS', 'Livraison de biens'), ('SERVICES', 'Prestation de services'), ('MIXED', 'Mixte (biens + services)')], default='SERVICES', help_text='Mention obligatoire dès 2026 (biens, services, mixte).', max_length=10, verbose_name='Type de transaction'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_payment_basis',
            field=models.CharField(choices=[('DEBITS', "TVA d'après les débits"), ('RECEIPTS', "TVA d'après les encaissements"), ('NA', 'Non applicable (franchise / exonération)')], default='NA', help_text='Pour services : encaissements (par défaut). Option débits sur facture.', max_length=10, verbose_name='Base de paiement TVA'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_identifier',
            field=models.CharField(blank=True, help_text='BT-155 — référence interne ou code produit (optionnel).', max_length=64, verbose_name='Identifiant article'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_code',
            field=models.CharField(choices=[('C62', 'One (unité, sans dimension)'), ('EA', 'Each (chaque)'), ('LS', 'Lump sum (forfait)'), ('HUR', 'Hour (heure)'), ('MIN', 'Minute'), ('DAY', 'Day (jour)'), ('WEE', 'Week (semaine)'), ('MON', 'Month (mois)'), ('ANN', 'Year (année)'), ('MTR', 'Metre (mètre)'), ('MTK', 'Square metre (m²)'), ('MTQ', 'Cubic metre (m³)'), ('KGM', 'Kilogram (kilogramme)'), ('GRM', 'Gram (gramme)'), ('TNE', 'Tonne (tonne métrique)'), ('LTR', 'Litre'), ('PCE', 'Piece (pièce)'), ('SET', 'Set (jeu)'), ('P1', 'Percent (pourcent)'), ('MGM', 'Megabyte'), ('GB', 'Gigabyte'), ('KWH', 'Kilowatt hour')], default='C62', help_text='C62=unité, HUR=heure, DAY=jour, MTR=mètre, LS=forfait...', max_length=4, verbose_name='Code unité (UN/ECE Rec 20)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='vat_category_code',
            field=models.CharField(choices=[('S', 'Standard rate (taux normal)'), ('Z', 'Zero rated goods (taux zéro)'), ('E', 'Exempt from tax (exonéré, ex. franchise en base)'), ('AE', 'VAT Reverse Charge (autoliquidation)'), ('K', 'VAT exempt for EEA intra-community supply'), ('G', 'Free export item, VAT not charged (export hors UE)'), ('O', 'Services outside scope of tax (hors champ)'), ('L', 'Canary Islands general indirect tax'), ('M', 'Tax for production, services and importation in Ceuta and Melilla')], default='E', help_text='S=normal, Z=zéro, E=exonéré (franchise), AE=autoliquidation, K=intra-UE.', max_length=2, verbose_name='Catégorie TVA (UNTDID 5305)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='vat_exemption_reason_code',
            field=models.CharField(blank=True, choices=[('VATEX-EU-79-C', 'Franchise en base de TVA (art. 293 B du CGI / art. 79c directive 2006/112/CE)'), ('VATEX-EU-AE', 'Reverse charge — autoliquidation par le preneur'), ('VATEX-EU-IC', 'Intra-community supply — livraison intracommunautaire (art. 138)'), ('VATEX-EU-G', 'Export outside the EU — exportation hors UE (art. 146)'), ('VATEX-EU-132', 'Exemption art. 132 directive 2006/112/CE'), ('VATEX-EU-132-1A', 'Services postaux publics (art. 132.1.a)'), ('VATEX-EU-132-1B', 'Hospitalisation et soins médicaux (art. 132.1.b)'), ('VATEX-EU-132-1C', 'Prestations de soins par professions médicales (art. 132.1.c)'), ('VATEX-EU-132-1I', 'Éducation (art. 132.1.i)'), ('VATEX-EU-132-1J', 'Cours particuliers (art. 132.1.j)'), ('VATEX-EU-143', 'Importations exonérées (art. 143)'), ('VATEX-EU-148', 'Opérations maritimes / aériennes (art. 148)'), ('VATEX-EU-151', 'Relations diplomatiques (art. 151)'), ('VATEX-EU-O', "Outside the scope of VAT — hors champ d'application TVA")], default='VATEX-EU-79-C', help_text='Obligatoire si vat_category_code ∈ {E, K, AE, G, O}. TUS franchise en base = VATEX-EU-79-C.', max_length=20, verbose_name="Motif d'exemption (VATEX)"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, help_text='Numéro FAC-AAAA-XXX, généré automatiquement si vide. Pour les avoirs : AVO-AAAA-XXXXX.', max_length=20, unique=True),
        ),
    ]
