# Generated by Django 5.2.10 on 2026-05-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0022_einvoicing_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='external_pdp_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID renvoyé par la PDP (B2Brouter ou autre) à la soumission.', max_length=64, verbose_name='Identifiant PDP externe'),
        ),
    ]
