# Generated by Django 6.0.2 on 2026-02-24 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('quote_created', 'Devis créé'), ('quote_sent', 'Devis envoyé'), ('quote_validated', 'Devis validé'), ('quote_accepted', 'Devis accepté'), ('quote_rejected', 'Devis refusé'), ('quote_invoiced', 'Devis facturé'), ('invoice_created', 'Facture créée'), ('invoice_sent', 'Facture envoyée'), ('invoice_paid', 'Facture payée'), ('invoice_marked_overdue', 'Facture marquée en retard'), ('milestone_validated', 'Jalon validé'), ('milestone_locked', 'Jalon verrouillé'), ('client_account_created', 'Compte client créé'), ('client_password_reset_forced', 'Réinitialisation de mot de passe forcée')], max_length=50, verbose_name="Type d'action")),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Horodatage')),
                ('content_type', models.CharField(help_text='devis.Quote, factures.Invoice, clients.ProjectMilestone, auth.User, etc.', max_length=50, verbose_name='Type de contenu')),
                ('object_id', models.PositiveIntegerField(help_text="pk de l'objet modifié", verbose_name="ID de l'objet")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données additionnelles : {old_value, new_value, ip, user_agent, comment, etc.}', verbose_name='Métadonnées')),
                ('description', models.TextField(blank=True, help_text="Résumé lisible de l'action", verbose_name='Description')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_created', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action_type', '-timestamp'], name='audit_audit_action__32de6f_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_997ff9_idx'), models.Index(fields=['actor', '-timestamp'], name='audit_audit_actor_i_dcd783_idx')],
            },
        ),
    ]
