# Generated by Django 6.0.2 on 2026-02-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('quote_created', 'Devis créé'), ('quote_sent', 'Devis envoyé'), ('quote_validated', 'Devis validé'), ('quote_accepted', 'Devis accepté'), ('quote_rejected', 'Devis refusé'), ('quote_invoiced', 'Devis facturé'), ('invoice_created', 'Facture créée'), ('invoice_sent', 'Facture envoyée'), ('invoice_paid', 'Facture payée'), ('invoice_marked_overdue', 'Facture marquée en retard'), ('milestone_validated', 'Jalon validé'), ('milestone_locked', 'Jalon verrouillé'), ('client_account_created', 'Compte client créé'), ('client_password_reset_forced', 'Réinitialisation de mot de passe forcée'), ('login_success', 'Connexion réussie'), ('login_failed', 'Tentative de connexion échouée'), ('rate_limit_hit', 'Limite de débit atteinte'), ('suspicious_activity', 'Activité suspecte détectée'), ('admin_action', 'Action admin')], max_length=50, verbose_name="Type d'action"),
        ),
    ]
