# Generated by Django 6.0.2 on 2026-03-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_add_security_event_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stripe Event Log',
                'verbose_name_plural': 'Stripe Event Logs',
                'indexes': [models.Index(fields=['-processed_at'], name='idx_stripe_event_date')],
            },
        ),
    ]
