# Generated by Django 5.2.10 on 2026-01-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise")),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Note sur 5', verbose_name='Note')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
