# Generated by Django 6.0.2 on 2026-03-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorQuotaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(verbose_name='User-Agent')),
                ('user_agent_hash', models.CharField(db_index=True, help_text='SHA256 hash for indexing (IP+UA is the unique key)', max_length=64, verbose_name='Hash User-Agent')),
                ('generation_count', models.PositiveIntegerField(default=1, verbose_name='Nombre de générations')),
                ('last_generation', models.DateTimeField(auto_now=True, verbose_name='Dernière génération')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise")),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Note sur 5', verbose_name='Note')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
