# Generated by Django 6.0.2 on 2026-03-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_simulatorquotausage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimulatorQuotaUsage',
        ),
    ]
