# Generated by Django 5.2.10 on 2026-06-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_simulatorquotausage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-review_published_at', '-created_at'], 'verbose_name': 'Témoignage', 'verbose_name_plural': 'Témoignages'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Avatar hébergé chez Google. Prioritaire sur le champ avatar uploadé si renseigné.', max_length=500, verbose_name='Photo distante (Google)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='google_review_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifiant unique fourni par Google (champ `name`). Vide pour les avis manuels.', max_length=255, verbose_name='Identifiant Google'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Mis à jour automatiquement à chaque exécution de `sync_google_reviews`.', null=True, verbose_name='Dernière synchro'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='review_published_at',
            field=models.DateTimeField(blank=True, help_text='Date de publication chez la source (Google) si connue.', null=True, verbose_name='Publié le'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='review_url',
            field=models.URLField(blank=True, help_text="URL publique de l'avis (Google) si disponible.", max_length=500, verbose_name="Lien vers l'avis"),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='source',
            field=models.CharField(choices=[('manual', 'Saisie manuelle (admin)'), ('google', 'Google Business Profile')], db_index=True, default='manual', max_length=16, verbose_name='Source'),
        ),
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.UniqueConstraint(condition=models.Q(('google_review_id__gt', '')), fields=('google_review_id',), name='unique_google_review_id'),
        ),
    ]
