# Generated by Django 5.2.10 on 2026-01-16 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devis', '0008_quote_deposit_paid_quote_deposit_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise")),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('siret', models.CharField(blank=True, max_length=14, verbose_name='SIRET')),
                ('tva_number', models.CharField(blank=True, max_length=20, verbose_name='N° TVA intracommunautaire')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='clients/avatars/', verbose_name='Photo de profil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil client',
                'verbose_name_plural': 'Profils clients',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('briefing', '📋 Cadrage'), ('design', '🎨 Design'), ('development', '💻 Développement'), ('review', '🔍 Recette'), ('delivered', '✅ Livré'), ('maintenance', '🔧 Maintenance')], default='briefing', max_length=20, verbose_name='Statut')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Progression (%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='Livraison estimée')),
                ('delivered_at', models.DateField(blank=True, null=True, verbose_name='Date de livraison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.clientprofile', verbose_name='Client')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='devis.quote', verbose_name='Devis associé')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('document_type', models.CharField(choices=[('brief', '📄 Cahier des charges'), ('logo', '🎨 Logo'), ('asset', '📦 Asset'), ('contract', '📝 Contrat'), ('other', '📎 Autre')], default='other', max_length=20, verbose_name='Type')),
                ('file', models.FileField(upload_to='clients/documents/%Y/%m/', verbose_name='Fichier')),
                ('uploaded_by_client', models.BooleanField(default=False, verbose_name='Uploadé par le client')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.clientprofile', verbose_name='Client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clients.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', '⏳ En attente'), ('in_progress', '🔄 En cours'), ('completed', '✅ Terminé')], default='pending', max_length=20, verbose_name='Statut')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='clients.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Jalon',
                'verbose_name_plural': 'Jalons',
                'ordering': ['order', 'due_date'],
            },
        ),
    ]
