# Generated by Django 6.0.2 on 2026-02-24 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientnotification_projectactivity_projectcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='Checklist JSON : [{id, text, checked, completed_by, completed_at}]', verbose_name='Checklist'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Personne responsable de ce jalon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de validation du jalon', null=True, verbose_name='Validé le'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a validé le jalon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='validation_comment',
            field=models.TextField(blank=True, help_text='Commentaire optionnel lors de la validation', verbose_name='Commentaire de validation'),
        ),
    ]
