# Generated by Django 6.0.2 on 2026-02-24 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_projectmilestone_checklist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Site Web Standard, App Mobile, Refonte UX', max_length=200, unique=True, verbose_name='Nom du workflow')),
                ('description', models.TextField(blank=True, help_text="Description du workflow et cas d'usage", verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Workflow disponible pour les nouveaux projets', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de workflow',
                'verbose_name_plural': 'Templates de workflows',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='workflow_template',
            field=models.ForeignKey(blank=True, help_text='Template utilisé pour générer les jalons', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='clients.workflowtemplate', verbose_name='Template de workflow'),
        ),
        migrations.CreateModel(
            name='MilestoneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Analyse des besoins, Design UI/UX, Développement', max_length=200, verbose_name='Titre du jalon')),
                ('description', models.TextField(blank=True, help_text='Description du jalon et livrables attendus', verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position dans le workflow (0 = premier)', verbose_name='Ordre')),
                ('checklist_template', models.JSONField(blank=True, default=list, help_text="Liste des tâches par défaut : [{text: 'Tâche 1'}, ...]", verbose_name='Checklist template')),
                ('estimated_duration_days', models.PositiveIntegerField(default=7, help_text='Durée estimée en jours pour ce jalon', verbose_name='Durée estimée (jours)')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_templates', to='clients.workflowtemplate', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Template de jalon',
                'verbose_name_plural': 'Templates de jalons',
                'ordering': ['workflow', 'order'],
                'unique_together': {('workflow', 'order')},
            },
        ),
    ]
