# Generated by Django 5.2.10 on 2026-01-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_projectactivity_projectcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientnotification',
            name='link',
        ),
        migrations.AddField(
            model_name='clientnotification',
            name='related_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL associée'),
        ),
    ]
