# Generated by Django 6.0.2 on 2026-02-25 00:32

from django.db import migrations, connection


def drop_industry_if_exists(apps, schema_editor):
    """Drop the orphan 'industry' column only if it exists."""
    with connection.cursor() as cursor:
        # SQLite: check pragma table_info
        cursor.execute("PRAGMA table_info(clients_clientprofile);")
        columns = [row[1] for row in cursor.fetchall()]
        if 'industry' in columns:
            cursor.execute('ALTER TABLE clients_clientprofile DROP COLUMN industry;')


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_workflowtemplate_project_workflow_template_and_more'),
    ]

    operations = [
        migrations.RunPython(drop_industry_if_exists, migrations.RunPython.noop),
    ]
