# Generated by Django 6.0.2 on 2026-02-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_orphan_industry_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Activé automatiquement lors de la création du compte. Désactivé après le premier changement de mot de passe.', verbose_name='Doit changer le mot de passe'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('brief', '📄 Cahier des charges'), ('logo', '🎨 Logo'), ('asset', '📦 Asset'), ('contract', '📝 Contrat'), ('devis', '💰 Devis'), ('facture', '🧾 Facture'), ('other', '📎 Autre')], default='other', max_length=20, verbose_name='Type'),
        ),
    ]
