# Generated by Django 5.2.10 on 2026-02-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_must_change_password_and_doc_types'),
        ('devis', '0010_quote_validated_at_quote_validated_audit_trail_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientnotification',
            index=models.Index(fields=['client', 'read'], name='idx_notif_client_read'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='idx_project_status'),
        ),
    ]
