# Generated by Django 6.0.2 on 2026-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientnotification_idx_notif_client_read_and_more'),
        ('devis', '0014_remove_quote_legacy_option_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='idx_project_status',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-created_at'], name='idx_project_status_date'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client', 'status'], name='idx_project_client_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workflow_template'], name='idx_project_workflow'),
        ),
    ]
