# Generated by Django 6.0.2 on 2026-02-27 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['client', '-created_at'], name='idx_document_client_date'),
        ),
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(fields=['project', '-created_at'], name='idx_activity_project_date'),
        ),
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(fields=['project', 'is_client_visible'], name='idx_activity_visible'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['project', 'is_internal'], name='idx_comment_project_internal'),
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['project', 'status'], name='idx_milestone_project_status'),
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['project', 'order'], name='idx_milestone_project_order'),
        ),
    ]
