# Generated by Django 6.0.2 on 2026-03-02 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nom complet'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse (texte libre)'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['email'], name='idx_client_email'),
        ),
    ]
