# Generated by Django 6.0.2 on 2026-03-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_populate_from_devis_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='read_by_admin',
            field=models.BooleanField(default=False, verbose_name="Lu par l'admin"),
        ),
    ]
