# Generated by Django 5.2.10 on 2026-03-27 18:00

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_add_read_by_admin_to_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='file',
            field=models.FileField(storage=core.utils.raw_media_storage, upload_to='clients/documents/%Y/%m/', verbose_name='Fichier'),
        ),
    ]
