# Generated by Django 5.2.10 on 2026-03-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('brief', '📄 Cahier des charges'), ('logo', '🎨 Logo'), ('asset', '📦 Asset'), ('contract', '📝 Contrat'), ('devis', '💰 Devis'), ('facture', '🧾 Facture'), ('video', '🎬 Vidéo'), ('audio', '🎵 Audio'), ('spreadsheet', '📊 Tableur'), ('presentation', '📽️ Présentation'), ('archive', '📁 Archive'), ('other', '📎 Autre')], default='other', max_length=20, verbose_name='Type'),
        ),
    ]
