# Generated by Django 5.2.10 on 2026-05-29 20:08

import apps.einvoicing.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_clientdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='country_code',
            field=models.CharField(default='FR', help_text='FR par défaut, BE/DE/LU... pour clients UE, autre pour hors UE.', max_length=2, verbose_name='Code pays (ISO 3166-1 alpha-2)'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='delivery_address_line',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse de livraison'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville (livraison)'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='delivery_country_code',
            field=models.CharField(blank=True, max_length=2, verbose_name='Pays (livraison)'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='delivery_zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code postal (livraison)'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='is_business',
            field=models.BooleanField(default=False, help_text='Coché pour B2B (déclenche les contrôles de SIREN/TVA).', verbose_name='Compte professionnel'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('AE', 'Auto-entrepreneur / micro-entreprise'), ('EI', 'Entreprise individuelle'), ('EURL', 'EURL (SARL unipersonnelle)'), ('SARL', 'SARL'), ('SAS', 'SAS'), ('SASU', 'SASU'), ('SA', 'SA'), ('SNC', 'SNC'), ('SCI', 'SCI'), ('SCOP', 'SCOP'), ('ASSO', 'Association'), ('PUB', 'Personne publique / collectivité'), ('OTH_FR', 'Autre (France)'), ('OTH_EU', 'Autre (Union européenne)'), ('OTH_INTL', 'Autre (hors UE)')], max_length=10, verbose_name='Forme juridique'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='peppol_id',
            field=models.CharField(blank=True, help_text='Format `<scheme>:<value>`, ex. `0009:90826411200016` (SIRET).', max_length=70, validators=[apps.einvoicing.validators.validate_peppol_id], verbose_name='Identifiant Peppol'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='siren',
            field=models.CharField(blank=True, help_text='9 chiffres. Obligatoire sur les factures B2B émises à partir du 1er sept. 2026.', max_length=9, validators=[apps.einvoicing.validators.validate_siren], verbose_name='SIREN'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='siret',
            field=models.CharField(blank=True, max_length=14, validators=[apps.einvoicing.validators.validate_siret], verbose_name='SIRET'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='tva_number',
            field=models.CharField(blank=True, max_length=20, validators=[apps.einvoicing.validators.validate_vat_intracom], verbose_name='N° TVA intracommunautaire'),
        ),
    ]
