# Generated by Django 5.2.10 on 2026-05-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_einvoicing_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifiant du Customer Stripe associé. Stripe collecte les tax_ids (SIREN/SIRET/TVA) au Checkout : ils sont remontés ici via le webhook customer.updated.', max_length=64, verbose_name='Stripe Customer ID'),
        ),
    ]
