# Migration manuelle : déplace SiteDiagnostic de audit vers diagnostic.
# Renomme la table audit_sitediagnostic → diagnostic_sitediagnostic
# et déclare le modèle dans l'état de l'app diagnostic.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0004_sitediagnostic"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="SiteDiagnostic",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("url", models.URLField(max_length=500, verbose_name="URL du site")),
                        ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date")),
                        ("status", models.CharField(choices=[("pending", "En attente"), ("running", "En cours"), ("completed", "Terminé"), ("failed", "Échoué")], default="pending", max_length=20, verbose_name="Statut")),
                        ("overall_score", models.PositiveSmallIntegerField(default=0, verbose_name="Score global")),
                        ("results", models.JSONField(blank=True, default=dict, verbose_name="Résultats")),
                        ("duration_seconds", models.FloatField(default=0, verbose_name="Durée (s)")),
                        ("error_message", models.TextField(blank=True, verbose_name="Erreur")),
                        ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="site_diagnostics", to=settings.AUTH_USER_MODEL, verbose_name="Lancé par")),
                    ],
                    options={
                        "verbose_name": "Diagnostic de site",
                        "verbose_name_plural": "Diagnostics de sites",
                        "ordering": ["-created_at"],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "audit_sitediagnostic" RENAME TO "diagnostic_sitediagnostic";',
                    reverse_sql='ALTER TABLE "diagnostic_sitediagnostic" RENAME TO "audit_sitediagnostic";',
                ),
            ],
        ),
    ]
# Generated by Django 5.2.12 on 2026-04-15 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL du site')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('overall_score', models.PositiveSmallIntegerField(default=0, verbose_name='Score global')),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='Résultats')),
                ('duration_seconds', models.FloatField(default=0, verbose_name='Durée (s)')),
                ('error_message', models.TextField(blank=True, verbose_name='Erreur')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_diagnostics', to=settings.AUTH_USER_MODEL, verbose_name='Lancé par')),
            ],
            options={
                'verbose_name': 'Diagnostic de site',
                'verbose_name_plural': 'Diagnostics de sites',
                'ordering': ['-created_at'],
            },
        ),
    ]
