# Generated by Django 5.2.10 on 2026-05-29 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('sector', models.CharField(blank=True, max_length=50, verbose_name='Secteur')),
                ('profile', models.CharField(choices=[('solo', 'TPE solo / Freelance'), ('pme', 'PME 3-15 personnes'), ('strategique', 'Réflexion stratégique')], default='pme', max_length=20, verbose_name='Profil')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='Interlocuteur')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, verbose_name="Notes d'entretien")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour')),
                ('overall_score', models.PositiveSmallIntegerField(default=0, verbose_name='Score global')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Réponses')),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='Analyse')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_diagnostics', to=settings.AUTH_USER_MODEL, verbose_name='Réalisé par')),
            ],
            options={
                'verbose_name': 'Diagnostic terrain',
                'verbose_name_plural': 'Diagnostics terrain',
                'ordering': ['-created_at'],
            },
        ),
    ]
