# Generated by Django 5.2.10 on 2026-05-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0002_fielddiagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddiagnostic',
            name='profile',
            field=models.CharField(choices=[('solo', 'Indépendant / Freelance'), ('tpe', 'TPE · 1 à 9 salariés'), ('pme', 'PME · 10 à 50 personnes'), ('croissance', 'Forte croissance / Scale-up'), ('reprise', 'Création / reprise récente'), ('strategique', 'Réflexion stratégique')], default='pme', max_length=20, verbose_name='Profil'),
        ),
    ]
