# Generated by Django 5.2.10 on 2026-05-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_alter_fielddiagnostic_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddiagnostic',
            name='sector',
            field=models.CharField(blank=True, choices=[('commerce', 'Commerce de détail / Négoce'), ('ecommerce', 'E-commerce / Vente en ligne'), ('restauration', 'Restauration / Café / Traiteur'), ('hotellerie', 'Hôtellerie / Hébergement'), ('tourisme', 'Tourisme / Loisirs / Activités'), ('services_pro', 'Services aux entreprises (B2B)'), ('services_part', 'Services aux particuliers (B2C)'), ('conseil', 'Conseil / Profession libérale'), ('sante', 'Santé / Bien-être / Paramédical'), ('beaute', 'Beauté / Coiffure / Esthétique'), ('artisanat', "Artisanat / Métiers d'art"), ('btp', 'BTP / Construction / Rénovation'), ('industrie', 'Industrie / Production'), ('transport', 'Transport / Logistique'), ('immobilier', 'Immobilier / Gestion locative'), ('formation', 'Formation / Éducation'), ('evenementiel', 'Événementiel / Communication'), ('agro', 'Agriculture / Pêche / Agroalimentaire'), ('numerique', 'Numérique / Tech / Studio'), ('association', 'Association / ESS'), ('autre', 'Autre activité')], max_length=50, verbose_name='Secteur'),
        ),
    ]
