# Generated by Django 5.2.10 on 2026-05-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0004_alter_fielddiagnostic_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddiagnostic',
            name='territory',
            field=models.CharField(blank=True, choices=[('guyane', 'Guyane'), ('martinique', 'Martinique'), ('guadeloupe', 'Guadeloupe'), ('reunion', 'La Réunion'), ('mayotte', 'Mayotte'), ('saint_martin', 'Saint-Martin'), ('saint_barth', 'Saint-Barthélemy'), ('polynesie', 'Polynésie française'), ('nouvelle_caledonie', 'Nouvelle-Calédonie'), ('hexagone', 'France hexagonale'), ('corse', 'Corse'), ('autre', 'Autre / Non précisé')], help_text="Territoire d'implantation : utilisé pour ajuster les seuils KPI (DSO, matelas, couverture) et déclencher les recommandations Outre-Mer.", max_length=30, verbose_name='Territoire'),
        ),
    ]
