# Generated by Django 5.2.10 on 2026-02-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='strategy',
            field=models.TextField(blank=True, default='', help_text='Ch.03 — Stratégie : méthodologie et processus déployés'),
        ),
        migrations.AlterField(
            model_name='project',
            name='objective',
            field=models.TextField(help_text='Ch.01 — Pourquoi : contexte et objectif du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='result',
            field=models.TextField(help_text='Ch.04 — Résultat : impact et livrables'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=models.TextField(help_text='Ch.02 — Défi technique : problème résolu et approche'),
        ),
    ]
