# Generated by Django 5.2.10 on 2026-02-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_add_strategy_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('site', 'Site'), ('commerce', 'Commerce'), ('outils', 'Outils métiers')], max_length=20),
        ),
    ]
