# Generated by Django 5.2.10 on 2026-02-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_update_project_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_ch02',
            field=models.ImageField(blank=True, help_text='Image Ch.02 — capture code ou maquette (1200×750 px idéal)', null=True, upload_to='portfolio/chapters/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_ch03',
            field=models.ImageField(blank=True, help_text='Image Ch.03 — architecture ou schéma (1920×820 px idéal)', null=True, upload_to='portfolio/chapters/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_ch04',
            field=models.ImageField(blank=True, help_text='Image Ch.04 — capture du résultat final (1920×1080 px idéal)', null=True, upload_to='portfolio/chapters/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='objective',
            field=models.TextField(help_text='Ch.01 — Pourquoi. Markdown supporté : **gras**, *italique*, - liste à puces'),
        ),
        migrations.AlterField(
            model_name='project',
            name='result',
            field=models.TextField(help_text='Ch.04 — Résultat. Markdown supporté : **gras**, *italique*, - liste à puces'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=models.TextField(help_text='Ch.02 — Défi technique. Markdown supporté : **gras**, *italique*, - liste à puces'),
        ),
        migrations.AlterField(
            model_name='project',
            name='strategy',
            field=models.TextField(blank=True, default='', help_text='Ch.03 — Stratégie. Markdown supporté : **gras**, *italique*, - liste à puces'),
        ),
    ]
