# Generated by Django 6.0.2 on 2026-02-23 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_add_chapter_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_label', models.CharField(help_text="Ex : Phase d'audit, Phase de conception, Phase de livraison", max_length=100)),
                ('title', models.CharField(help_text='Ex : Analyse & Exploration, Architecture & Prototypage', max_length=200)),
                ('description', models.TextField(help_text='Description de cette phase (2-3 phrases).')),
                ('icon', models.CharField(choices=[('search', '🔍 Analyse / Audit'), ('architecture', '📦 Architecture / Conception'), ('deploy', '✦ Déploiement / Livraison'), ('code', '💻 Code / Développement'), ('design', '🎨 Design / UX'), ('database', '🗄️ Base de données'), ('security', '🔒 Sécurité'), ('performance', '⚡ Performance'), ('test', '✅ Tests / QA'), ('meeting', '🤝 Échange / Cadrage')], default='search', help_text='Icône affichée à côté de la phase.', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier).")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_phases', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Phase de stratégie',
                'verbose_name_plural': 'Phases de stratégie',
                'ordering': ['order'],
            },
        ),
    ]
