# Generated by Django 6.0.2 on 2026-02-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_add_strategy_phase'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', '-created_at'], name='idx_portfolio_published'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type', 'is_published'], name='idx_portfolio_type'),
        ),
    ]
