"""URL configuration for the simulateur app."""
from django.urls import path

from .views import (
    AcseView,
    AtterrissageView,
    CacView,
    CapaciteView,
    CorrelationView,
    CoutInactionView,
    CoutNonQualiteView,
    CoutPromotionView,
    DelegationView,
    DependanceView,
    EffortImpactView,
    ElasticiteView,
    FragmentationView,
    FrictionView,
    HubView,
    JumeauxClientsView,
    MixProduitsView,
    PlafondView,
    PointMortView,
    PricingPaliersView,
    PrixPsychologiqueView,
    RetentionView,
    RoiMarketingView,
    SaisonnaliteView,
    ScenarioPivotView,
    SimulateurView,
    TailleMarcheView,
    TresorerieView,
    ValeurSortieView,
    ValleeMortView,
    VulnerabileFournisseurView,
)

app_name = 'simulateur'

urlpatterns = [
    path('', HubView.as_view(), name='hub'),
    path('devis/', SimulateurView.as_view(), name='devis'),
    # ── 10 outils existants ──
    path('point-mort/', PointMortView.as_view(), name='point-mort'),
    path('cac/', CacView.as_view(), name='cac'),
    path('friction/', FrictionView.as_view(), name='friction'),
    path('fragmentation/', FragmentationView.as_view(), name='fragmentation'),
    path('acse/', AcseView.as_view(), name='acse'),
    path('plafond/', PlafondView.as_view(), name='plafond'),
    path('elasticite/', ElasticiteView.as_view(), name='elasticite'),
    path('vallee-mort/', ValleeMortView.as_view(), name='vallee-mort'),
    path('retention/', RetentionView.as_view(), name='retention'),
    # ── 20 nouveaux outils ──
    path('mix-produits/', MixProduitsView.as_view(), name='mix-produits'),
    path('atterrissage/', AtterrissageView.as_view(), name='atterrissage'),
    path('tresorerie/', TresorerieView.as_view(), name='tresorerie'),
    path('jumeaux-clients/', JumeauxClientsView.as_view(), name='jumeaux-clients'),
    path('correlation/', CorrelationView.as_view(), name='correlation'),
    path('delegation/', DelegationView.as_view(), name='delegation'),
    path('prix-psychologique/', PrixPsychologiqueView.as_view(), name='prix-psychologique'),
    path('dependance/', DependanceView.as_view(), name='dependance'),
    path('capacite/', CapaciteView.as_view(), name='capacite'),
    path('saisonnalite/', SaisonnaliteView.as_view(), name='saisonnalite'),
    path('cout-promotion/', CoutPromotionView.as_view(), name='cout-promotion'),
    path('valeur-sortie/', ValeurSortieView.as_view(), name='valeur-sortie'),
    path('effort-impact/', EffortImpactView.as_view(), name='effort-impact'),
    path('cout-inaction/', CoutInactionView.as_view(), name='cout-inaction'),
    path('scenario-pivot/', ScenarioPivotView.as_view(), name='scenario-pivot'),
    path('roi-marketing/', RoiMarketingView.as_view(), name='roi-marketing'),
    path('pricing-paliers/', PricingPaliersView.as_view(), name='pricing-paliers'),
    path('taille-marche/', TailleMarcheView.as_view(), name='taille-marche'),
    path('vulnerabilite-fournisseur/', VulnerabileFournisseurView.as_view(), name='vulnerabilite-fournisseur'),
    path('cout-non-qualite/', CoutNonQualiteView.as_view(), name='cout-non-qualite'),
]
